tap "caskroom/cask"
tap "getantibody/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "mas-cli/tap"
brew "archey"
brew "bash"
brew "bash-completion"
brew "bat"
brew "sqlite"
brew "cairo"
brew "calc"
brew "cocoapods", link: false
brew "coreutils"
brew "dbus"
brew "exercism"
brew "fdk-aac"
brew "harfbuzz"
brew "python"
brew "libbluray"
brew "sdl2"
brew "ffmpeg"
brew "findutils"
brew "gd"
brew "git"
brew "grep"
brew "mecab"
brew "mecab-ipadic"
brew "msgpack"
brew "groonga"
brew "httrack"
brew "libplist"
brew "ideviceinstaller"
brew "ios-webkit-debug-proxy"
brew "jansson"
brew "jemalloc"
brew "krb5"
brew "libav"
brew "libev"
brew "libgpg-error"
brew "libgcrypt"
brew "libmaxminddb"
brew "mpfr"
brew "libmpc"
brew "libsmi"
brew "libssh"
brew "libxml2"
brew "lua@5.1"
brew "mariadb"
brew "mas"
brew "namebench"
brew "neovim"
brew "nghttp2"
brew "nmap"
brew "node"
brew "ntfs-3g"
brew "postgresql"
brew "protobuf"
brew "speedtest-cli"
brew "stow"
brew "tmux"
brew "tree"
brew "unrar"
brew "watchman"
brew "wget"
brew "wireshark"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "getantibody/tap/antibody"
cask "appcleaner"
cask "calibre"
cask "firefox"
cask "font-awesome-terminal-fonts"
cask "gimp"
cask "google-chrome"
cask "iterm2"
cask "postman"
cask "qbittorrent"
cask "virtualbox"
cask "vlc"
mas "Amphetamine", id: 937984704
mas "Coin Tick", id: 1141688067
mas "Keyboard Virtuoso Light", id: 1202560697
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Parallels Desktop", id: 1085114709
mas "SnippetsLab", id: 1006087419
mas "The Unarchiver", id: 425424353
mas "Typist", id: 415166115
mas "VOX", id: 461369673
mas "Xcode", id: 497799835
mas "Zen Pinball 2", id: 527953383
